"""Perf: add indexes to PaymentTransaction for faster queries

Revision ID: d74031182a92
Revises: 01ccdfbe3757
Create Date: 2025-12-03 20:37:05.445021

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd74031182a92'
down_revision = '01ccdfbe3757'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payment_transaction', schema=None) as batch_op:
        batch_op.create_index('idx_payment_tx_created_at', ['created_at'], unique=False)
        batch_op.create_index('idx_payment_tx_member_year_month', ['member_id', 'year', 'month'], unique=False)
        batch_op.create_index(batch_op.f('ix_payment_transaction_member_id'), ['member_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_payment_transaction_year'), ['year'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payment_transaction', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_payment_transaction_year'))
        batch_op.drop_index(batch_op.f('ix_payment_transaction_member_id'))
        batch_op.drop_index('idx_payment_tx_member_year_month')
        batch_op.drop_index('idx_payment_tx_created_at')

    # ### end Alembic commands ###
